#!/bin/bash
cd /tmp

# 加载 VNC（如果开启的话）
if [[ -f ~/.config/GXDE/gxde-x11vnc ]]; then
	if [[ -f ~/.vnc/passwd ]]; then
		nohup x11vnc --forever -rfbauth ~/.vnc/passwd &
	else
		nohup x11vnc --forever &  # 免密
	fi
fi
