#!/bin/bash

set -e
echo "version,codename,series,created,release,eol" > /usr/share/distro-info/deepin.csv
echo "15.2,Unstable,unstable,2016-06-01" >> /usr/share/distro-info/deepin.csv
echo "15.3,Unstable,unstable,2016-09-13" >> /usr/share/distro-info/deepin.csv
echo "15.4,Panda,panda,2017-04-19" >> /usr/share/distro-info/deepin.csv

arch=$(dpkg --print-architecture)
isDebian12=$(cat /etc/debian_version | grep 12 | wc -l)
#if [[ $arch != "amd64" ]] && [[ $arch != "arm64" ]] && [[ isDebian12 != "" ]] && [[ ! -f /etc/apt/sources.list.d/debian.list ]] && [[ -f /tmp/debian-backports.list ]] && [[ ! -f /etc/deepin/calamares ]]; then
#	cp -v /tmp/debian-backports.list /etc/apt/sources.list.d/debian.list
#fi

case "${1}" in
	configure)
		# nmbd 服务还是会有问题
		 systemctl disable nmbd.service | true

	    update-alternatives --install /etc/deepin-version \
		    deepin-version /usr/lib/deepin/desktop-version 50
		# 修改 os-release
		# 
#		if [[ $(cat /usr/lib/os-release | grep GXDE | wc -l) != "0" ]]; then
			cp -rv /usr/lib/deepin/os-release /usr/lib/os-release || true
#		fi
	    if [ -x /usr/sbin/update-initramfs ]
	    then
		    update-initramfs -u
	    fi

        if [ -x /usr/sbin/update-grub ]
        then
            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
        fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac

# 因为现在该 deb 包已移除该配置文件，但同时为了保证之前用户的兼容性，在已经开启 backport 源的系统
# 备份 backport 源防止被 dpkg 自动移除导致依赖问题
# 该步为还原文件
if [[ -f /etc/apt/preferences.d/90bookworm-backports-bak ]]; then
    mv /etc/apt/preferences.d/90bookworm-backports-bak /etc/apt/preferences.d/90bookworm-backports
fi
#DEBHELPER#

exit 0
