#!/bin/bash

set -e
echo "version,codename,series,created,release,eol" > /usr/share/distro-info/deepin.csv
echo "15.2,Unstable,unstable,2016-06-01" >> /usr/share/distro-info/deepin.csv
echo "15.3,Unstable,unstable,2016-09-13" >> /usr/share/distro-info/deepin.csv
echo "15.4,Panda,panda,2017-04-19" >> /usr/share/distro-info/deepin.csv

arch=$(dpkg --print-architecture)
isDebian12=$(cat /etc/debian_version | grep 12 | wc -l)
if [[ $arch != "amd64" ]] && [[ $arch != "arm64" ]] && [[ isDebian12 != "" ]] && [[ ! -f /etc/apt/sources.list.d/debian.list ]] && [[ ! -f /tmp/debian-backports.list ]]; then
	cp -v /tmp/debian-backports.list /etc/apt/sources.list.d/debian.list
fi

case "${1}" in
	configure)
		# 禁用有问题的 nmbd 服务
		systemctl disable nmbd.service | true

	    update-alternatives --install /etc/deepin-version \
		    deepin-version /usr/lib/deepin/desktop-version 50
		# 修改 os-release
		cp -r /usr/lib/deepin/os-release /usr/lib/os-release || true
	    if [ -x /usr/sbin/update-initramfs ]
	    then
		    update-initramfs -u
	    fi

        if [ -x /usr/sbin/update-grub ]
        then
            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
        fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac

#DEBHELPER#

exit 0
