#!/bin/bash

set -e
echo "version,codename,series,created,release,eol" > /usr/share/distro-info/deepin.csv
echo "15.2,Unstable,unstable,2016-06-01" >> /usr/share/distro-info/deepin.csv
echo "15.3,Unstable,unstable,2016-09-13" >> /usr/share/distro-info/deepin.csv
echo "15.4,Panda,panda,2017-04-19" >> /usr/share/distro-info/deepin.csv

arch=$(dpkg --print-architecture)

case "${1}" in
	configure)
		# nmbd 服务还是会有问题
		 systemctl disable nmbd.service | true

		if [[ -e /usr/lib/deepin/desktop-version ]]; then
	    	update-alternatives --install /etc/deepin-version \
		    	deepin-version /usr/lib/deepin/desktop-version 50
		fi

		# 修改 os-release
		if [[ -e /usr/lib/deepin/os-release ]]; then
			cp -rv /usr/lib/deepin/os-release /usr/lib/os-release || true
		fi
		for NAME in $(ls /usr/lib/deepin/);do
            if [ ! -L /etc/$NAME ];then
                rm -vf /etc/$NAME
            fi
            update-alternatives --install /etc/$NAME $NAME /usr/lib/deepin/$NAME  50
        done
#		fi
	    if [ -x /usr/sbin/update-initramfs ]
	    then
		    update-initramfs -u
	    fi

        if [ -x /usr/sbin/update-grub ]
        then
            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
        fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;
	triggered)

		if [[ -e /usr/lib/deepin/desktop-version ]]; then
	    	update-alternatives --install /etc/deepin-version \
		    	deepin-version /usr/lib/deepin/desktop-version 50
		fi
		# 修改 os-release
		if [[ -e /usr/lib/deepin/os-release ]]; then
			cp -rv /usr/lib/deepin/os-release /usr/lib/os-release || true
		fi
		for NAME in $(ls /usr/lib/deepin/);do
    	    if [ ! -L /etc/$NAME ];then
            	rm -vf /etc/$NAME
            fi
            update-alternatives --install /etc/$NAME $NAME /usr/lib/deepin/$NAME  50
        done
		;;
	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac

# 因为现在该 deb 包已移除该配置文件，但同时为了保证之前用户的兼容性，在已经开启 backport 源的系统
# 备份 backport 源防止被 dpkg 自动移除导致依赖问题
# 该步为还原文件
if [[ -f /etc/apt/preferences.d/90bookworm-backports-bak ]]; then
    mv /etc/apt/preferences.d/90bookworm-backports-bak /etc/apt/preferences.d/90bookworm-backports
fi
#DEBHELPER#

exit 0
